apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hebbs.fullname" . }}-config
  labels:
    {{- include "hebbs.labels" . | nindent 4 }}
data:
  hebbs.toml: |
    {{- .Values.config | nindent 4 }}
